### ISSUE TITLE
Copy & Paste Error

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [IntuitDeveloper/OAuth2-Dotnet-WithoutSDK#1]
https://github.com/IntuitDeveloper/OAuth2-Dotnet-WithoutSDK/blob/b6a40b18ad08d561bc9eae8300816e87ab1a7d12/OAuth2_SampleApp_Dotnet/OAuth2Manager.aspx.cs#L802

This should say key.E

**Comment by nimisha84** [comment]
Updated sample code
